# Generated by Django 5.0 on 2025-05-24 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='supplier',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='last_restocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='reorder_level',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='InventoryModel',
        ),
    ]
