# Generated by Django 5.0 on 2025-05-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_productmodel_cost_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='last_restocked',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.categorymodel'),
            preserve_default=False,
        ),
    ]
