# Generated by Django 5.0 on 2025-05-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_productmodel_last_restocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
