# Generated by Django 5.0 on 2025-05-24 11:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
        ('inventory', '0004_alter_suppliermodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity_left', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='inventory.productmodel')),
            ],
            options={
                'verbose_name': 'Stock In Record',
                'verbose_name_plural': 'Stock In Records',
                'ordering': ['-date_added', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockInSummaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='The overall date of this stock-in summary.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this summary record was created.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created this summary.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('products', models.ManyToManyField(blank=True, help_text='Individual stock-in records included in this summary.', to='inventory.stockinmodel')),
            ],
            options={
                'verbose_name': 'Stock In Summary',
                'verbose_name_plural': 'Stock In Summaries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_removed', models.DecimalField(decimal_places=2, help_text='Quantity of product removed.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost_of_removed_stock', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated cost of the stock removed based on costing method.', max_digits=10, null=True)),
                ('reason', models.TextField(help_text="Why was this stock removed (e.g., 'Damaged', 'Internal Use', 'Lost').")),
                ('date_removed', models.DateField(default=django.utils.timezone.now, help_text='The date this stock was physically removed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who recorded this stock out.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='inventory.productmodel')),
            ],
            options={
                'verbose_name': 'Stock Out Record',
                'verbose_name_plural': 'Stock Out Records',
                'ordering': ['-date_removed', '-created_at'],
            },
        ),
    ]
