# Generated by Django 5.0 on 2025-05-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_saleitemmodel_discount_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinmodel',
            name='quantity_sold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
