# Generated by Django 5.0 on 2025-05-28 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
        ('inventory', '0007_stockinmodel_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
    ]
