# Generated by Django 5.0 on 2025-05-30 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_salemodel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockoutmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='inventory.stockinmodel'),
        ),
    ]
