# Generated by Django 5.0 on 2025-05-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_stockoutmodel_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockoutmodel',
            old_name='product',
            new_name='stock',
        ),
    ]
