# Generated by Django 5.0 on 2025-05-30 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_product_stockoutmodel_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinmodel',
            name='quantity_stocked_out',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockoutmodel',
            name='date_removed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='The date this stock was physically removed.'),
        ),
    ]
