# Generated by Django 5.0 on 2025-05-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/student_images')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('class_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_site.classsectionmodel')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_site.classesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFundingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='images/funding')),
                ('reference', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_list', to='student.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentWalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('student', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to='student.studentmodel')),
            ],
        ),
    ]
