# Generated by Django 5.0 on 2025-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwalletmodel',
            name='debt',
            field=models.FloatField(default=0.0),
        ),
    ]
