# Generated by Django 5.0 on 2025-05-23 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentwalletmodel_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfundingmodel',
            name='method',
            field=models.CharField(blank=True, choices=[('offline', 'OFFLINE'), ('online', 'ONLINE')], default='offline', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentwalletmodel',
            name='student',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_wallet', to='student.studentmodel'),
        ),
    ]
