# Generated by Django 5.0 on 2025-05-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_studentfundingmodel_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfundingmodel',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
