# Generated by Django 5.0 on 2025-05-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentfundingmodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfundingmodel',
            name='balance',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
