# Generated by Django 5.0 on 2025-05-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentfundingmodel_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='barcode',
            field=models.FileField(blank=True, null=True, upload_to='barcode/student'),
        ),
    ]
