# Generated by Django 5.0 on 2025-05-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentmodel_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfundingmodel',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='teller_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
