# Generated by Django 5.0 on 2025-05-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentfundingmodel_decline_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfundingmodel',
            name='reference',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
