# Generated by Django 5.0 on 2025-05-31 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
        ('student', '0009_studentfundingmodel_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfundingmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded this stock out.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded this stock out.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.CreateModel(
            name='FingerprintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_name', models.CharField(max_length=50)),
                ('fingerprint_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='student.studentmodel')),
            ],
        ),
    ]
