# Generated by Django 5.0 on 2025-08-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_studentfundingmodel_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwalletmodel',
            name='meal',
            field=models.IntegerField(default=0),
        ),
    ]
