# Generated by Django 5.0 on 2025-05-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=200)),
                ('logo', models.FileField(blank=True, upload_to='images/logo')),
                ('mobile_1', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_student_debt', models.BooleanField(default=True)),
                ('auto_low_balance_notification', models.BooleanField(default=True)),
                ('max_student_debt', models.FloatField()),
                ('low_balance', models.FloatField()),
                ('allow_refund', models.BooleanField(default=False)),
                ('auto_generate_student_id', models.BooleanField(default=True)),
                ('term', models.CharField(choices=[('1st term', '1st TERM'), ('2nd term', '2nd TERM'), ('3rd term', '3rd TERM')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('seperator', models.CharField(choices=[('-', '-'), ('/', '/')], max_length=1)),
            ],
        ),
        migrations.AddConstraint(
            model_name='classsectionmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_class_name_type_combo'),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='section',
            field=models.ManyToManyField(blank=True, to='admin_site.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='schoolsettingmodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.sessionmodel'),
        ),
        migrations.AddConstraint(
            model_name='classesmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name_class_type_combo'),
        ),
    ]
