# Generated by Django 5.0 on 2025-05-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolinfomodel',
            old_name='mobile_1',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='schoolinfomodel',
            name='website',
        ),
    ]
