# Generated by Django 5.0 on 2025-05-23 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_rename_mobile_1_schoolinfomodel_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettingmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AlterField(
            model_name='schoolsettingmodel',
            name='term',
            field=models.CharField(blank=True, choices=[('1st term', '1st TERM'), ('2nd term', '2nd TERM'), ('3rd term', '3rd TERM')], max_length=10, null=True),
        ),
    ]
