# Generated by Django 5.0 on 2025-05-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_alter_schoolsettingmodel_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classesmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='classsectionmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
