# Generated by Django 5.0 on 2025-05-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_alter_classesmodel_name_alter_classsectionmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSectionInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_site.classsectionmodel')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.classesmodel')),
                ('form_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.teachermodel')),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.AddConstraint(
            model_name='classsectioninfomodel',
            constraint=models.UniqueConstraint(fields=('student_class', 'section'), name='unique_student_class_section_combo'),
        ),
    ]
