# Generated by Django 5.0 on 2025-05-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0006_alter_teachermodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettingmodel',
            name='use_barcode_scanner',
            field=models.BooleanField(default=False),
        ),
    ]
