# Generated by Django 5.0 on 2025-08-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0010_activitylogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettingmodel',
            name='meal_cost',
            field=models.FloatField(default=0),
        ),
    ]
